services:
  backend:
    build: ./backend
    container_name: llm-analytics-backend
    ports:
      - "8003:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
      - ./datasets:/datasets
      - ./outputs:/outputs
    environment:
      OLLAMA_BASE_URL: http://host.docker.internal:11434
      OLLAMA_MODEL: qwen3:8b
      LAB2_DATASET_FILENAME: customer_reviews
      LAB3_PLANNER_MODEL: qwen3:8b
      LAB3_TOOL_CALLER_MODEL: qwen2.5-coder:7b
      LAB3_CRITIC_MODEL: deepseek-r1:8b
      DATASETS_DIR: /datasets
      OUTPUTS_DIR: /outputs

  frontend:
    build: ./frontend
    container_name: llm-analytics-frontend
    ports:
      - "3003:3000"
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8003/api


